DROP TABLE IF EXISTS config_properties CASCADE;
DROP TABLE IF EXISTS configurations CASCADE;
DROP TABLE IF EXISTS reset_password_requests CASCADE;
DROP TABLE IF EXISTS confirm_tokens CASCADE;
DROP TABLE IF EXISTS social_network_auths CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP TYPE IF EXISTS AUTH_AUTHORITY;
DROP TYPE IF EXISTS AUTH_SOCIAL_NETWORK_TYPE;
DROP TYPE IF EXISTS AUTH_TOKEN_TYPE;